Repository FC-DEV-FinalProject/FinalProject_Be3C_FE, pull requests merged in 2024-11, with the labels that each got.

#5 [settings] 라우팅 작업 완료
  package-lock.json
  package.json
  src/App.tsx
  src/constants/path.ts
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/pages/Faq.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/Notices.tsx
  src/pages/NoticesDetail.tsx
  src/pages/QnaAdd.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/StrategyAdd.tsx
  src/pages/StrategyDetail.tsx
  src/pages/StrategyList.tsx
  src/pages/StrategySearch.tsx
  src/pages/Temp.tsx
  src/pages/TraderList.tsx
  src/pages/TraderStrategyInfo.tsx
  src/pages/TraderStrategyList.tsx
  src/pages/UserStrategyInfo.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/AdminMethods.tsx
  src/pages/admin/AdminNoticeAdd.tsx
  src/pages/admin/AdminNoticeEdit.tsx
  src/pages/admin/AdminNotices.tsx
  src/pages/admin/AdminQna.tsx
  src/pages/admin/AdminStocks.tsx
  src/pages/admin/AdminStrategies.tsx
  src/pages/admin/AdminUsers.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyPageCheck.tsx
  src/pages/mypage/MyQnaEdit.tsx
  src/pages/mypage/MyStrategyEdit.tsx
  src/pages/mypage/MyStrategyList.tsx
  src/pages/mypage/Profile.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/mypage/TraderQnaList.tsx
  src/pages/mypage/UserQnaList.tsx
  src/pages/mypage/Withdraw.tsx
  src/routes/Router.tsx
Labels: ⚙️ Settings

#6 [settings] 전역 스타일 작업
  package-lock.json
  package.json
  src/App.tsx
  src/layouts/Layout.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyles.tsx
  tsconfig.app.json
Labels: ⚙️ Settings

#8 [fix] Layout CSS 수정
  src/layouts/Layout.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyles.tsx
Labels: 🛠️ Fix

#15 [fix] 라우팅 수정 작업
  src/constants/path.ts
  src/layouts/SignupStepLayout.tsx
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignUpDone.tsx
  src/pages/SignUpForm.tsx
  src/pages/SignUpType.tsx
  src/pages/Temp.tsx
  src/pages/UserStrategyInfo.tsx
  src/routes/Router.tsx
Labels: 🛠️ Fix

#13 [style] Footer 컴포넌트 퍼블리싱 작업
  src/assets/images/simbol.png
  src/layouts/Footer.tsx
  src/layouts/Layout.tsx
Labels: 🎨 Style

#12 [style] 로그인페이지 퍼블리싱 및 간단한 기능 추가
  package-lock.json
  package.json
  src/layouts/Layout.tsx
  src/pages/SignIn.tsx
Labels: 🎨 Style

#23 [style] 회원가입 페이지 퍼블리싱
  src/layouts/Layout.tsx
  src/layouts/SignupStepLayout.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/SignUpDone.tsx
  src/pages/SignUpForm.tsx
  src/pages/SignUpType.tsx
Labels: 🎨 Style

#38 [settings] API 호출 구조화 작업
  package-lock.json
  package.json
  src/api/adminApi.ts
  src/api/axiosInstance.ts
  src/api/commonApi.ts
  src/api/strategyApi.ts
  src/api/userApi.ts
  src/main.tsx
Labels: ⚙️ Settings

#40 [feat] 공통컴포넌트 프로필이미지 작업
  src/components/ProfileImage.tsx
Labels: ✨ Feature

#43 [settings] 상수 파일 세팅 작업
  src/constants/color.ts
  src/constants/font.ts
  src/styles/GlobalStyles.tsx
Labels: ⚙️ Settings

#45 [feat] Pagination 컴포넌트 구현
  src/components/Pagination.tsx
  src/constants/color.ts
  src/layouts/Header.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature

#46 [feat] button 컴포넌트 구현
  src/components/Button.tsx
  src/components/ProfileImage.tsx
  src/constants/color.ts
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature

#47 [feat] checkbox 컴포넌트 구현
  src/components/Checkbox.tsx
  src/constants/color.ts
Labels: ✨ Feature

#50 [feat] Calendar 컴포넌트 구현
  src/components/Calendar.tsx
  src/components/Pagination.tsx
  src/layouts/Header.tsx
Labels: ✨ Feature

#59 [feat] RadioButton 컴포넌트 구현
  src/components/RadioButton.tsx
Labels: ✨ Feature

#55 [feat] TabButton 컴포넌트 구현
  src/components/TabButton.tsx
Labels: ✨ Feature

#57 [fix] Button 및 IconButton 컴포넌트 수정
  src/components/Button.tsx
  src/components/IconButton.tsx
  src/pages/SignIn.tsx
Labels: 🛠️ Fix

#63 [feat] ToTopButton 컴포넌트 구현
  src/components/IconButton.tsx
  src/components/ToTopButton.tsx
Labels: ✨ Feature

#68 [fix] Footer 컴포넌트 수정
  src/layouts/Footer.tsx
  src/layouts/Layout.tsx
Labels: 🛠️ Fix

#71 [feat] Comment 컴포넌트 구현
  src/components/Comment.tsx
  src/constants/color.ts
  src/layouts/Header.tsx
  src/utils/dateUtils.ts
Labels: ✨ Feature

#70 [style] 메인 페이지 퍼블리싱 작업
  src/assets/images/test-profile.png
  src/components/VerticalCarousel.tsx
  src/pages/Home.tsx
Labels: 🎨 Style

#69 [fix] Button, TabButton 컴포넌트 수정
  src/components/Button.tsx
  src/components/TabButton.tsx
Labels: 🛠️ Fix

#72 [feat] Toggle 컴포넌트 구현
  src/components/Toggle.tsx
Labels: ✨ Feature

#66 [feat] TextArea 컴포넌트 구현
  src/components/TextArea.tsx
Labels: ✨ Feature

#44 [feat] TextInput 컴포넌트 구현
  src/components/IconButton.tsx
  src/components/ProfileImage.tsx
  src/components/TextInput.tsx
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature

#86 [feat] SelectBox 컴포넌트 구현
  src/components/SelectBox.tsx
Labels: ✨ Feature

#85 [style] 전략 탐색 페이지 퍼블리싱 작업
  src/components/Button.tsx
  src/components/Checkbox.tsx
  src/components/ProfileImage.tsx
  src/components/RadioButton.tsx
  src/components/TabButton.tsx
  src/components/TextArea.tsx
  src/components/TextInput.tsx
  src/constants/path.ts
  src/layouts/StrategyListLayout.tsx
  src/mocks/traders.json
  src/pages/StrategyAddInfo.tsx
  src/pages/StrategyList.tsx
  src/pages/StrategyQna.tsx
  src/pages/TraderList.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/AdminUsers.tsx
  src/routes/Router.tsx
  src/types/strategyFilter.ts
Labels: ✨ Feature

#88 [fix] SelectBox 컴포넌트 수정사항 반영
  src/components/SelectBox.tsx
  src/components/TextInput.tsx
Labels: 🛠️ Fix

#89 [style] 전략 등록 페이지 퍼블리싱 작업
  index.html
  public/favicon.ico
  src/pages/StrategyAdd.tsx
Labels: 🎨 Style

#91 [style] 마이페이지 상담 투자자용 퍼블리싱
  src/assets/images/test-tag.jpg
  src/components/Button.tsx
  src/constants/path.ts
  src/layouts/MyPageLayout.tsx
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
  src/pages/mypage/MyPageOpt.tsx
  src/pages/mypage/MyQnaEdit.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/QnaList.tsx
  src/routes/Router.tsx
Labels: 🎨 Style

#94 [fix] SelectBox 옵션 선택 시 반환 데이터 수정
  src/components/SelectBox.tsx
Labels: 🛠️ Fix

#95 [feat] Table 컴포넌트 구현
  src/components/Table.tsx
  src/constants/path.ts
  src/layouts/Footer.tsx
  src/pages/mypage/QnaAnswer.tsx
  src/routes/Router.tsx
  src/stores/useTableStore.ts
Labels: ✨ Feature

#96 [style] 트레이더별 전략상세 페이지 퍼블리싱
  src/mocks/strategies.json
  src/pages/TraderStrategyList.tsx
Labels: 🎨 Style

#97 [style] 마이페이지(메인) 퍼블리싱 작업
  src/layouts/MyPageLayout.tsx
  src/pages/TraderStrategyList.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyStrategyList.tsx
Labels: 🎨 Style

#100 [style] 마이페이지(상담문의_답변) 퍼블리싱 작업
  src/components/Table.tsx
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
  src/pages/mypage/MyQnaEdit.tsx
  src/pages/mypage/QnaAnswer.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/QnaList.tsx
Labels: 🎨 Style

#101 [style] 관리자 페이지(회원관리) 퍼블리싱
  src/constants/path.ts
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/pages/Home.tsx
  src/pages/Policy.tsx
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/StrategyAdd.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/AdminUsers.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyPageCheck.tsx
  src/pages/mypage/QnaAnswer.tsx
  src/pages/mypage/QnaList.tsx
  src/routes/Router.tsx
Labels: 🎨 Style

#102 [feat] Chart 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Chart.tsx
  src/components/ToTopButton.tsx
  src/layouts/Footer.tsx
  src/mocks/chart.json
  src/pages/Home.tsx
  src/pages/TraderList.tsx
  src/pages/TraderStrategyList.tsx
  src/pages/mypage/MyPage.tsx
Labels: ✨ Feature

#106 [style] 관리자 페이지(회원관리) 퍼블리싱 최신화 작업
  src/components/TextInput.tsx
  src/mocks/users.json
  src/pages/admin/AdminUsers.tsx
Labels: 🎨 Style

#107 [style] 마이페이지(내정보변경) 퍼블리싱 작업
  src/components/Button.tsx
  src/components/IconButton.tsx
  src/components/TabButton.tsx
  src/components/Table.tsx
  src/components/VerticalCarousel.tsx
  src/layouts/MyPageLayout.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
  src/pages/StrategyList.tsx
  src/pages/mypage/MyPageOpt.tsx
  src/pages/mypage/MyPagePassword.tsx
  src/pages/mypage/Profile.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/mypage/QnaAnswer.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/Withdraw.tsx
Labels: 🎨 Style

#104 [feat] Modal 컴포넌트 구현
  src/components/Chart.tsx
  src/components/Modal.tsx
  src/components/VerticalCarousel.tsx
  src/layouts/Footer.tsx
  src/pages/TraderList.tsx
  src/pages/TraderStrategyList.tsx
  src/stores/useModalStore.ts
Labels: ✨ Feature

#103 [settings] 개발용 Netlify 배포 작업
  .gitignore
  env.d.ts
  public/_redirects
  src/api/axiosInstance.ts
  src/config.ts
  tsconfig.app.json
Labels: ⚙️ Settings

#114 [style] 전략 상세 페이지 퍼블리싱 작업
  src/assets/images/default-profile.png
  src/assets/images/facebook-icon.png
  src/assets/images/kakaotalk-icon.png
  src/assets/images/x-icon.png
  src/components/Button.tsx
  src/components/ProfileImage.tsx
  src/components/TabButton.tsx
  src/components/TextArea.tsx
  src/components/TextInput.tsx
  src/constants/path.ts
  src/layouts/MyPageLayout.tsx
  src/layouts/StrategyDetailLayout.tsx
  src/mocks/comment.json
  src/mocks/strategy-monthly.json
  src/pages/QnaAdd.tsx
  src/pages/QnaQuestion.tsx
  src/pages/StrategyAdd.tsx
  src/pages/StrategyDetail.tsx
  src/pages/StrategyDetailAccount.tsx
  src/pages/StrategyDetailDaily.tsx
  src/pages/StrategyDetailMonthly.tsx
  src/pages/StrategyQna.tsx
  src/pages/StrategySearch.tsx
  src/pages/admin/AdminStrategiesControl.tsx
  src/pages/mypage/MyPageOpt.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/Withdraw.tsx
  src/routes/Router.tsx
Labels: 🎨 Style

#118 [feat] Loading 컴포넌트 구현
  src/components/Loading.tsx
Labels: ✨ Feature

#112 [style] 기타 페이지(2) 퍼블리싱 작업
  src/pages/Faq.tsx
Labels: 🎨 Style

#127 [feat] RangeSlider 컴포넌트 구현
  src/components/Checkbox.tsx
  src/components/RangeSlider.tsx
Labels: ✨ Feature

#128 [style] 전략 수정(관리) 페이지 퍼블리싱 작업
  src/components/TabButton.tsx
  src/layouts/StrategyDetailLayout.tsx
  src/mocks/strategy-weekly.json
  src/pages/admin/AdminStrategiesControl.tsx
  src/pages/mypage/MyStrategyEdit.tsx
Labels: 🎨 Style

#129 [style] 404 페이지 퍼블리싱 작업
  src/assets/images/page-not-found.png
  src/components/Checkbox.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
Labels: 🎨 Style

#130 [feat] Breadcrumb 컴포넌트 구현
  src/components/Breadcrumb.tsx
  src/constants/color.ts
  src/constants/path.ts
  src/layouts/Header.tsx
  src/pages/admin/AdminNoticesDetail.tsx
  src/routes/Router.tsx
Labels: ✨ Feature

#115 [feat] 로그인 페이지 기능 구현
  src/api/authApi.ts
  src/api/axiosInstance.ts
  src/api/index.ts
  src/hooks/useAuthApi.ts
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
Labels: ✨ Feature

#137 [fix] Modal 컴포넌트 수정
  src/components/Checkbox.tsx
  src/components/Modal.tsx
  src/components/Table.tsx
  src/stores/useModalStore.ts
Labels: 🛠️ Fix

#138 [settings] API 공통 로직 구현 및 함수 생성
  src/api/adminApi.ts
  src/api/authApi.ts
  src/api/commonApi.ts
  src/api/strategyApi.ts
  src/api/userApi.ts
  src/hooks/useAdminApi.ts
  src/hooks/useAuthApi.ts
  src/hooks/useCommonApi.ts
  src/hooks/useStrategyApi.ts
  src/hooks/useUserApi.ts
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/utils/authUtils.ts
Labels: ⚙️ Settings

#140 [style] 관리자 페이지(문의관리) 퍼블리싱 작업
  src/components/Table.tsx
  src/constants/path.ts
  src/mocks/qna.json
  src/pages/admin/AdminQna.tsx
  src/pages/admin/AdminQnaDetail.tsx
  src/routes/Router.tsx
Labels: 🎨 Style

#142 [feat] 로그인 회원 정보 전역 상태 관리 기능 구현
  src/App.tsx
  src/api/authApi.ts
  src/hooks/useAuthApi.ts
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/stores/useAuthStore.ts
  src/utils/authUtils.ts
Labels: ✨ Feature

#113 [style] 관리자 페이지(전략관리) 퍼블리싱 작업
  src/components/TextArea.tsx
  src/layouts/AdminStrategyLayout.tsx
  src/mocks/adminMethods.json
  src/mocks/adminStocks.json
  src/mocks/adminStrategies.json
  src/pages/admin/AdminMethods.tsx
  src/pages/admin/AdminStocks.tsx
  src/pages/admin/AdminStrategies.tsx
Labels: 🎨 Style

#144 [feat] Tooltip 컴포넌트 구현
  src/components/Tooltip.tsx
Labels: ✨ Feature

#145 [feat] 전략 등록 페이지 기능 구현
  src/api/strategyApi.ts
  src/assets/images/day-icon.png
  src/assets/images/position-icon.png
  src/assets/images/strategy-add-page.png
  src/components/Chart.tsx
  src/components/Modal.tsx
  src/components/TextInput.tsx
  src/hooks/useAuthApi.ts
  src/hooks/useStrategyAdd.ts
  src/hooks/useStrategyApi.ts
  src/pages/SignIn.tsx
  src/pages/StrategyAdd.tsx
  src/stores/useAuthStore.ts
Labels: ✨ Feature
