Repository FC-DEV-FinalProject/FinalProject_Be3C_FE, pull requests merged in 2024-12, with the labels that each got.

#139 [feat] 계정 및 비밀번호 찾기 페이지 기능 구현
  src/api/authApi.ts
  src/hooks/useAuthApi.ts
  src/pages/SignFindId.tsx
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
  src/stores/useAuthStore.ts
Labels: ✨ Feature

#148 [settings] 구글 애널리틱스 태그 추가
  index.html
Labels: ⚙️ Settings

#146 [style] 기타 페이지(1) 퍼블리싱 작업
  src/pages/Policy.tsx
Labels: 🎨 Style

#150 [feat] useCountMotion 공통 Hook 구현
  src/hooks/useCountMotion.ts
Labels: ✨ Feature

#131 [feat] 회원가입 페이지 기능 구현
  src/api/authApi.ts
  src/assets/images/congratulation.png
  src/components/Button.tsx
  src/components/Calendar.tsx
  src/components/IconButton.tsx
  src/components/TextInput.tsx
  src/components/signup/Dot.tsx
  src/components/signup/Terms.tsx
  src/components/signup/TermsCommon.tsx
  src/hooks/useAuthApi.ts
  src/layouts/SignupStepLayout.tsx
  src/pages/SignUp.tsx
  src/pages/SignUpDone.tsx
  src/pages/SignUpForm.tsx
  src/pages/SignUpType.tsx
Labels: ✨ Feature

#154 [feat] 마이페이지(전략) 기능 구현
  src/api/strategyApi.ts
  src/hooks/useStrategyApi.ts
  src/layouts/MyPageLayout.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyStrategyList.tsx
  src/stores/useAuthStore.ts
  src/utils/tableUtils.ts
Labels: ✨ Feature

#155 [feat] 전략 수정(관리) 페이지 기능 구현
  src/api/adminApi.ts
  src/api/authApi.ts
  src/api/strategyApi.ts
  src/components/Calendar.tsx
  src/components/IconButton.tsx
  src/components/SelectBox.tsx
  src/components/Table.tsx
  src/components/TextInput.tsx
  src/hooks/useAdminApi.ts
  src/hooks/useAdminStrategiesControl.ts
  src/hooks/useAuthApi.ts
  src/hooks/useMyStrategyEdit.ts
  src/hooks/useStrategyAdd.ts
  src/hooks/useStrategyApi.ts
  src/mocks/notice-admin.json
  src/mocks/strategy-daily.json
  src/mocks/strategy-weekly.json
  src/pages/StrategyAdd.tsx
  src/pages/admin/AdminStrategiesControl.tsx
  src/pages/mypage/MyStrategyEdit.tsx
  src/utils/dataUtils.ts
Labels: ✨ Feature

#132 [feat] 마이페이지(회원/상담) 기능 구현
  src/api/commonApi.ts
  src/api/strategyApi.ts
  src/api/userApi.ts
  src/assets/images/withdraw1.png
  src/assets/images/withdraw2.png
  src/assets/images/withdraw3.png
  src/components/ProfileImage.tsx
  src/components/RangeSlider.tsx
  src/hooks/useCommonApi.ts
  src/hooks/useUserApi.ts
  src/layouts/MyPageLayout.tsx
  src/layouts/StrategyDetailLayout.tsx
  src/mocks/faq-list.json
  src/pages/Faq.tsx
  src/pages/QnaQuestion.tsx
  src/pages/SignIn.tsx
  src/pages/mypage/MyPageOpt.tsx
  src/pages/mypage/MyPagePassword.tsx
  src/pages/mypage/MyQnaEdit.tsx
  src/pages/mypage/Profile.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/mypage/QnaAnswer.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/QnaList.tsx
  src/pages/mypage/Withdraw.tsx
Labels: ✨ Feature

#152 [feat] 전략 탐색 페이지 기능 구현
  src/components/StrategyFilter.tsx
  src/hooks/useStrategyFilters.ts
  src/pages/StrategyList.tsx
  src/pages/TraderList.tsx
  src/pages/TraderStrategyInfo.tsx
  src/pages/TraderStrategyList.tsx
  src/types/strategyFilter.ts
Labels: ✨ Feature

#157 [feat] 공지사항 페이지 기능 구현
  src/api/adminApi.ts
  src/api/commonApi.ts
  src/hooks/useAdminApi.ts
  src/hooks/useCommonApi.ts
  src/pages/Notices.tsx
  src/pages/NoticesDetail.tsx
  src/pages/admin/AdminNoticesDetail.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/QnaList.tsx
Labels: ✨ Feature

#158 [feat] 전략 상세 페이지 기능 구현
  src/api/strategyApi.ts
  src/assets/images/kakaotalk-icon.png
  src/components/Comment.tsx
  src/components/DetailCard.tsx
  src/components/TextArea.tsx
  src/constants/color.ts
  src/hooks/useAdminStrategiesControl.ts
  src/hooks/useCountMotion.ts
  src/hooks/useMyStrategyEdit.ts
  src/hooks/useStrategyApi.ts
  src/layouts/StrategyDetailLayout.tsx
  src/pages/NotFound.tsx
  src/pages/StrategyDetail.tsx
  src/pages/StrategyDetailAccount.tsx
  src/pages/StrategyDetailDaily.tsx
  src/pages/StrategyDetailMonthly.tsx
  src/pages/admin/AdminStrategiesControl.tsx
  src/pages/mypage/MyStrategyEdit.tsx
  src/utils/dataUtils.ts
Labels: ✨ Feature

#162 [feat] 관리자 페이지(공지관리) 기능 구현
  src/api/adminApi.ts
  src/hooks/useAdminApi.ts
  src/layouts/MyPageLayout.tsx
  src/pages/Notices.tsx
  src/pages/NoticesDetail.tsx
  src/pages/admin/AdminNoticeAdd.tsx
  src/pages/admin/AdminNoticeEdit.tsx
  src/pages/admin/AdminNotices.tsx
  src/pages/admin/AdminNoticesDetail.tsx
Labels: ✨ Feature

#165 [feat] 프로젝트 부가 기능 구현 및 수정사항 반영 작업
  src/api/strategyApi.ts
  src/assets/images/cms-logo.png
  src/components/auth/RequireAdmin.tsx
  src/components/auth/RequireAuth.tsx
  src/hooks/useAuthApi.ts
  src/hooks/useMyStrategyEdit.ts
  src/hooks/useStrategyApi.ts
  src/layouts/AdminStrategyLayout.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/layouts/MyPageLayout.tsx
  src/layouts/StrategyDetailLayout.tsx
  src/layouts/StrategyListLayout.tsx
  src/routes/Router.tsx
  src/stores/useAuthStore.ts
Labels: ✨ Feature

#163 [fix] 프로젝트 디자인 수정사항 반영 작업
  src/api/adminApi.ts
  src/components/Chart.tsx
  src/components/StrategyFilter.tsx
  src/components/TabButton.tsx
  src/hooks/useMyStrategyEdit.ts
  src/hooks/useStrategyAdd.ts
  src/layouts/MyPageLayout.tsx
  src/layouts/StrategyDetailLayout.tsx
  src/pages/Home.tsx
  src/pages/StrategyAdd.tsx
  src/pages/StrategyDetail.tsx
  src/pages/StrategyDetailDaily.tsx
  src/pages/StrategyDetailMonthly.tsx
  src/pages/StrategyList.tsx
  src/pages/TraderStrategyList.tsx
  src/pages/admin/AdminStrategiesControl.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyStrategyEdit.tsx
  src/pages/mypage/MyStrategyList.tsx
Labels: 🛠️ Fix

#164 [feat] 관리자 페이지(회원관리) 기능 구현
  src/api/adminApi.ts
  src/api/authApi.ts
  src/hooks/useAdminApi.ts
  src/pages/admin/AdminUsers.tsx
Labels: ✨ Feature

#166 [feat] 관리자 페이지(전략목록) 일부 기능 구현
  src/api/adminApi.ts
  src/hooks/useAdminApi.ts
  src/layouts/AdminStrategyLayout.tsx
  src/pages/admin/AdminMethods.tsx
  src/pages/admin/AdminStocks.tsx
Labels: ✨ Feature

#172 [documents] 리드미 파일 작성
  README.md
Labels: 📃 Documents
